titanium
copper ore
copper wire: 2 copper ore
silver ore
fabricator: table coral sample, titanium, gold
radio: titanium, copper ore
medical kit fabricator: computer chip, fiber mesh, silver ore, titanium
fiber mesh: 2 creepvine sample
titanium ingot: 10 titanium
silicone rubber: creepvine seed cluster
glass: 2 quartz
bleach: salt deposit, coral tube sample
lubricant: creepvine seed cluster
enameled glass: stalker tooth, glass
plasteel ingot: titanium ingot, 2 lithium
hydrochloric acid: 3 deep shroom, salt deposit
benzene: 3 blood oil
synthetic fibers: benzene, fiber mesh
aerogel: gel sack, ruby
polyaniline: gold, hydrochloric acid
battery: 2 acid mushroom, copper ore
power cell: 2 battery, silicone rubber
computer chip: 2 table coral sample, gold, copper wire
wiring kit: 2 silver ore
advanced wiring kit: wiring kit, 2 gold, computer chip
reactor rod: 3 uranininite crystal, lead, titanium, glass
filtered water: bladderfish
disinfected water: bleach
multipurpose room: 6 titanium
moonpool: 2 titanium ingot, lubricant, 2 lead
reinforcement: lithium, 3 titanium
bulkhead: 3 titanium, silicone rubber
locker: quartz, 2 titanium
battery charger: wiring kit, copper wire, titanium
power cell charger: advanced wiring kit, 2 ruby, 2 titanium
basic plant pot: 2 titanium
composite plant pot: 2 titanium
chic plant pot: 2 titanium
indoor growbed: 4 titanium
plant shelf: titanium
trash can: 2 titanium
single bed: titanium, fiber mesh
basic double bed: 2 titanium, fiber mesh
window: glass
hatch: quartz, 2 titanium
I compartment: 2 titanium
L compartment: 2 titanium
T compartment: 3 titanium
X compartment: 3 titanium
I Glass compartment: 2 glass
L Glass compartment: 2 glass
Vertical connector: 2 titanium
